---
title: "Diabetes Prediction Model"
author: "Hayes Liu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

## Load data

```{r}
#start here
library(tidyverse)
library(caret)
library(Metrics)  #to do light metrics calculations 
dataset <- read_csv("diabetes.csv")
glimpse(dataset)
```

## Data processing

```{r}
#Data Processing
#----------------------------------------
#Checked for missing values
colSums(is.na(dataset))

#Separated features (X) and target variable (y).
target_y<-dataset$Outcome
feature_x<-dataset %>% select(-Outcome)
glimpse(feature_x)
glimpse(target_y)

#Scaled only the features to standardize their values
#it basically just means findinng z using z=(x-mean)/sd
#"center" subtracts the column's mean from every value
#"scale" divides by the standard deviation
pp <- preProcess(feature_x, method = c("center", "scale")) 
#scale the features
scaled <- predict(pp, feature_x)
glimpse(scaled)
final_dataset<-tibble(scaled,target_y)
final_dataset<-final_dataset%>%
  mutate(Row_ID=row_number())
glimpse(final_dataset)

#spilt the data into 70/30
set.seed(12345)
training<-final_dataset %>%
  slice_sample(n=round(768*0.7,0))
glimpse(training)

testing<-anti_join(final_dataset,training,by="Row_ID")
glimpse(testing)

training <- training %>% select(-Row_ID)
testing <- testing %>% select(-Row_ID)
```

## Data visualisation

```{r}
#Data visulisation 
#---------------------------------------------------------
#visualize the distribution of the Outcome variable (whether or not a person has diabetes) using bar graph 
Outcome_cat<-as.factor(dataset$Outcome)
ggplot(data=dataset)+
  geom_bar(mapping=aes(x=Outcome_cat))+
  labs(x="Outcome")

# visualized the distribution of Pregnancies with respect to the Outcome using histogram 
ggplot(data=dataset,mapping=aes(x=Pregnancies,fill = Outcome_cat))+
  geom_histogram(boundary=0,binwidth = 1,color = "black")+
  facet_wrap(~Outcome)

#Boxplot for BMI by Outcome
ggplot(data=dataset,mapping=aes(x=Outcome_cat,y=BMI,fill=Outcome_cat))+
  geom_boxplot()+
  labs(x="Outcome")

#Scatter plot with trend lines for DiabetesPedigreeFunction against SkinThickness based on the Outcome 
ggplot(data = dataset,
       mapping = aes(x = SkinThickness, y = DiabetesPedigreeFunction,
                     colour = Outcome_cat)) +
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE) 
```

## Building the model and making predictions

```{r}
#Building the model+ making prediction based on it 
#-----------------------------------------------------------
#building a logistic regression model to predict the outcome based on the features
training_model<-glm(as.factor(target_y)~.,binomial,training)

#make a prediction using the testing dataset
test_prob  <- predict(training_model,testing , type="response")
#change the probabilithy in to 1 if it is more than a half
test_class <- ifelse(test_prob >= 0.5, 1, 0)


#calculating the precison(the proportion of positive predictions that are correct)
precision_score <- precision(testing$target_y,test_class)

#calculating the recall(the proportion of actual positive cases correctly identified
recall_score <- recall(testing$target_y,test_class)

#calculating the F1-Score(mean of Precision and Recall)
F1_score <- 2 * (precision_score * recall_score) / (precision_score + recall_score)

print(precision_score)
print(recall_score)
print(F1_score)
```

## Prediction function

```{r}
#a function to test the likelihood of having diabetes using patient data
predict_fun=function(Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,
                     DiabetesPedigreeFunction,Age){
  data<-tibble(Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,
               DiabetesPedigreeFunction,Age)
  data <- predict(pp, data)
  answer<-predict(training_model,data, type="response")
  if(answer<0.5){print("The chance u have diabetes is relatively low ")}else{print("The chance u have diabetes is relatively high")}
  return(answer)
}

#a working example 
predict_fun(4,45,26,79,84,16.6,0.351,24)
```